const data =[

   {    id:1,
       name:"Sagittarius",
       info:"Sagittarius is the ninth astrological sign, which is associated with the constellation Sagittarius and spans 240–270th degrees of the zodiac. Under the tropical zodiac, the sun transits this sign between approximately November 22 and December 21 and under the sidereal zodiac from December 18 - January 15",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502369/zodiac-signs/sagittarius_zfmues.png",
       element:"fire",
       Symbol: "Archer",
       colors:"Purple, dark blue, plum.",
       Planet: "Jupiter",
       hour1:1,
       hour2:2,

   },
   {    id:2,
       name:"Scopio",
       info:"Scorpio is the eighth astrological sign in the zodiac, originating from the constellation of Scorpius. It spans 210°–240° ecliptic longitude. Under the tropical zodiac, the Sun transits this sign on average from October 23 to November 22.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502369/zodiac-signs/Scorpio_ypps3m.png",
       element:"Water",
       Symbol:"Scorpion",
       colors:"deep red, maroon, black, and brown.",
       Planet:"Pluto, Mars",
       hour1:3,
       hour2:4,

   },
   {    id:3,
       name:"Libra",
       info:"Libra is the seventh astrological sign in the zodiac. It spans 180°–210° celestial longitude. The Sun transits this sign on average between September 23 and October 23. Under the sidereal zodiac, the Sun currently transits the constellation of Libra from approximately October 31 to November 22.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502369/zodiac-signs/libra_ag96py.png",
       element:"Air",
       Symbol:"Scales",
       colors:"pink and blue",
       Planet:"Venus",
       hour1:5,
       hour2:6,

   },
   {    id:4,
       name:"Virgo",
       info:"Virgo is the sixth astrological sign in the Zodiac. It spans the 150–180th degree of the zodiac. Under the tropical zodiac, the Sun transits this area, on average, between August 23 and September 22, while the Sun transits the Virgo from approximately September 16 to October 30.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502369/zodiac-signs/virgo_w5mkl3.png",
       element:"Earth",
       Symbol:"Maiden",
       colors:"green and brown.",
       Planet:"Mercury",
       hour1:7,
       hour2:8,
   },
   {    id:5,
       name:"Leo",
       info:"Leo, Latin for Lion, is the fifth sign of the zodiac. It corresponds to the constellation Leo and comes after Cancer and before Virgo. The traditional Western zodiac associates Leo with the period between July 23 and August 22, and the sign spans the 120th to 150th degree of celestial longitude.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502369/zodiac-signs/leo_kgjxmq.png",
       element:"Fire",
       Symbol:"Lion",
       colors:"orange",
       Planet:"Sun",
       hour1:9,
       hour2:10,

   },
   {    id:6,
       name:"Cancer",
       info:"Cancer is the fourth astrological sign in the zodiac, originating from the constellation of Cancer. It spans from 90° to 120° celestial longitude.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502368/zodiac-signs/cancer_bgmiw7.png",
       element:"Water",
       Symbol:"Crab",
       colors:"blue, white and sea green",
       Planet:"Mars",
       hour1:11,
       hour2:12,

   },
   {    id:7,
       name:"Gemini",
       info:"Gemini is the third astrological sign in the zodiac. Under the tropical zodiac, the sun transits this sign between about May 21 to June 21. Under the sidereal zodiac, the sun transits this sign from about June 16 to July 16.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502368/zodiac-signs/gemini_iboxoc.png",
       element:"Air",
       Symbol:"Twin",
       colors:"green",
       Planet:"Mercury",
       hour1:13,
       hour2:14,
   },
   {    id:8,
       name:"Taurus",
       info:"Taurus is an earth sign represented by the bull. Like their celestial spirit animal, Taureans enjoy relaxing in serene, bucolic environments, surrounded by soft sounds, soothing aromas, and succulent flavors. Taurus is ruled by Venus, the enchanting planet that governs love, beauty, and money.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502369/zodiac-signs/Taurus_grfbeu.png",
       element:"Earth",
       Symbol:"Bull",
       colors:"green",
       Planet:"Mars, Pluto",
       hour1:15,
       hour2:16,

   },
   {    id:9,
       name:"Aries",
       info:"Aries is the first astrological sign in the zodiac, spanning the first 30 degrees of celestial longitude, and originates from the constellation of the same name. Under the tropical zodiac, the Sun transits this sign from approximately March 20 to April 21 each year.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502368/zodiac-signs/Aries_xdtqy1.png",
       element:"Fire",
       Symbol:"Ram",
       colors:"red",
       Planet:"Mars",
       hour1:17,
       hour2:18,

   },
   {    id:10,
       name:"Pisces",
       info:"Pisces is the twelfth and final astrological sign in the zodiac. It is a negative, mutable sign. It spans 330° to 360° of celestial longitude. Under the tropical zodiac, the sun transits this area between February 19 and March 20.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502369/zodiac-signs/Pisces_zdaohc.png",
       element:"Water",
       Symbol:"Fish",
       colors:"Seafoam Green",
       Planet:"Neptune.",
       hour1:19,
       hour2:20,

   },
   {    id:11,
       name:"Aquarius",
       info:"Aquarius, the 11th zodiac sign, is symbolised by the Water Bearer, a symbol of the Gods bringing essential nutrients to the Earth. Aquarius people are advanced, self-reliant, clever, exceptional, and optimistic. Air is their elemental sign. Aquarians, like air, lack a distinct form and appear to resist classification.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502368/zodiac-signs/aquarius_xkczkb.png",
       element:"Air",
       Symbol:" Water-Bearer",
       colors:"blue",
       Planet:"Uranus.",
       hour1:21,
       hour2:22,

   },
   {    id:12,
       name:"Capricor",
       info:"Capricorn is the tenth astrological sign in the zodiac out of twelve total zodiac signs, originating from the constellation of Capricornus, the horned goat. It spans the 270–300th degree of the zodiac, corresponding to celestial longitude.",
       image:"https://res.cloudinary.com/fullupe/image/upload/v1651502368/zodiac-signs/carpricorn_khnkdt.png",
       element:"Earth",
       Symbol:"Sea-Goat",
       colors:"brown and gray",
       Planet:"Saturn.",
       hour1:23,
       hour2:0,

   },

 


]

export default data
    